name: Publish Docker image
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push ref
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: fleadram/grpc-wiremock:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push latest
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: fleadram/grpc-wiremock:latest
          platforms: linux/amd64,linux/arm64
